spring.application.name=backend

# ===============================
# 1. DATABASE CONNECTION (Aiven Cloud MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://mysql-3fedf9b-movieticket-fullstack.d.aivencloud.com:20545/ticketmoviedb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_AIVEN_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# 2. JPA / HIBERNATE CONFIGURATION
# ===============================
# T? ??ng ??ng b? các class Entity thành b?ng trong Database
spring.jpa.hibernate.ddl-auto=update

# Ch?n ph??ng ng? MySQL ?? Hibernate d?ch code t?i ?u nh?t
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hi?n th? và format các câu l?nh SQL trên console ?? ti?n debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
